// Bake the georeferenced base-map ortho for the qanat window into assets/.
// Fetches the Luxembourg national orthophoto (ACT, geoportail.lu open data, INSPIRE WMS)
// for GEO_BBOX as a single georeferenced JPEG, and records provenance in data/ortho.json.
//
// The image is committed to the repo (the static build never refetches), so this runs
// on-demand, not in predev/prebuild. Network required. Usage: node scripts/bake-ortho.mjs
import { writeFileSync } from 'node:fs';

// Must match index.html GEO_BBOX so the drape's per-vertex UV = lon/lat fraction.
const GEO_BBOX = { west: 6.138, east: 6.162, south: 49.6618, north: 49.6708 };
const LAYER = 'OI_OrthoimageCoverage_RGB_2019';   // matches the 2019 ACT LiDAR terrain epoch
const YEAR = 2019;
const WIDTH = 4096;   // ~0.42 m/px over the window (2019 ACT ortho native GSD is 0.20 m)

// Keep pixels ~square in ground metres (lon-metres : lat-metres at this latitude).
const midLat = (GEO_BBOX.south + GEO_BBOX.north) / 2;
const mPerDegLon = 111320 * Math.cos(midLat * Math.PI / 180);
const lonM = (GEO_BBOX.east - GEO_BBOX.west) * mPerDegLon;
const latM = (GEO_BBOX.north - GEO_BBOX.south) * 111320;
const HEIGHT = Math.round(WIDTH * latM / lonM);

// WMS 1.3.0 with EPSG:4326 uses lat,lon axis order → bbox = south,west,north,east.
const url = 'https://wms.inspire.geoportail.lu/geoserver/oi/ows'
  + '?service=WMS&version=1.3.0&request=GetMap'
  + '&layers=' + LAYER + '&styles='
  + '&crs=EPSG:4326'
  + '&bbox=' + [GEO_BBOX.south, GEO_BBOX.west, GEO_BBOX.north, GEO_BBOX.east].join(',')
  + '&width=' + WIDTH + '&height=' + HEIGHT
  + '&format=image/jpeg';

const OUT_IMG = new URL('../assets/ortho-walferdange.jpg', import.meta.url);
const OUT_META = new URL('../data/ortho.json', import.meta.url);

console.log('› fetching ACT ortho', LAYER, WIDTH + '×' + HEIGHT, '…');
const res = await fetch(url);
const ct = res.headers.get('content-type') || '';
if (!res.ok || !ct.startsWith('image/')) {
  const body = await res.text().catch(() => '');
  console.error('✗ ortho fetch failed: http', res.status, ct, '\n', body.slice(0, 400));
  process.exit(1);
}
const buf = Buffer.from(await res.arrayBuffer());
writeFileSync(OUT_IMG, buf);
console.log('› wrote assets/ortho-walferdange.jpg (' + buf.length + ' bytes)');

const meta = {
  _doc: 'GENERATED by scripts/bake-ortho.mjs — provenance for the base-map drape texture '
    + '(assets/ortho-walferdange.jpg). bbox matches index.html GEO_BBOX so per-vertex UV = '
    + 'lon/lat fraction. Present-day imagery for spatial context, distinct from the '
    + 'reconstructed Roman archaeology.',
  ortho: {
    id: 'raschpetzer-ortho',
    provider: 'ACT (Administration du cadastre et de la topographie), Luxembourg',
    service: 'geoportail.lu INSPIRE WMS',
    layer: LAYER,
    year: YEAR,
    bbox: GEO_BBOX,
    epsg: 4326,
    imagePx: [WIDTH, HEIGHT],
    approxGroundResM: +(lonM / WIDTH).toFixed(2),
    file: 'assets/ortho-walferdange.jpg',
    source: 'geoportail_lu',
    status: 'documented',
    note: 'Draped on the LiDAR terrain for spatial context; matches the 2019 ACT LiDAR epoch.'
  }
};
writeFileSync(OUT_META, JSON.stringify(meta, null, 2) + '\n');
console.log('› wrote data/ortho.json');
