// Bake forest/hiking paths around the qanat into assets/paths-walferdange.js.
// Source: OpenStreetMap (via Overpass) — geoportail.lu has no clean path VECTOR layer
// (only the topo_tour_20k tourist raster), so paths come from OSM, attributed as such.
// Fetches highway=path/track/footway/bridleway ways for a padded window and writes a
// window.RASCH_PATHS global (loaded via <script>, like assets/vectors-walferdange.js).
//
// Committed to the repo (the static build never refetches). Network required.
// Usage: node scripts/bake-paths.mjs
import { writeFileSync } from 'node:fs';

const AREA = { south: 49.655, west: 6.125, north: 49.678, east: 6.175 };
const Q = '[out:json][timeout:30];'
  + `way["highway"~"^(path|track|footway|bridleway)$"](${AREA.south},${AREA.west},${AREA.north},${AREA.east});`
  + 'out geom;';

console.log('› fetching OSM paths via Overpass …');
const res = await fetch('https://overpass-api.de/api/interpreter', {
  method: 'POST',
  headers: { 'User-Agent': 'raschpetzer-viz/1.0', 'Accept': 'application/json' },
  body: 'data=' + encodeURIComponent(Q)
});
if (!res.ok) { console.error('✗ Overpass failed: http', res.status); process.exit(1); }
const data = await res.json();
const ways = (data.elements || []).filter(e => e.type === 'way' && Array.isArray(e.geometry));
// Each path → array of [lon,lat] (rounded), dropping degenerate 1-point ways.
const paths = ways
  .map(w => w.geometry.map(p => [+p.lon.toFixed(6), +p.lat.toFixed(6)]))
  .filter(p => p.length >= 2);

const payload = {
  _doc: 'GENERATED by scripts/bake-paths.mjs — forest/hiking paths (OpenStreetMap, '
    + 'highway=path/track/footway/bridleway) as draped polylines. Coords are WGS84 lon/lat.',
  meta: { source: 'OpenStreetMap contributors', license: 'ODbL', area: AREA },
  paths
};
const out = new URL('../assets/paths-walferdange.js', import.meta.url);
writeFileSync(out, '// GENERATED by scripts/bake-paths.mjs — DO NOT EDIT. Run `npm run bake:paths`.\n'
  + 'window.RASCH_PATHS = Object.freeze(' + JSON.stringify(payload) + ');\n');
const verts = paths.reduce((a, p) => a + p.length, 0);
console.log(`› wrote assets/paths-walferdange.js (${paths.length} paths, ${verts} vertices)`);
