// Bake the SSOT: validate → write data.bundle.js (window.SSOT) → generate RASCHPETZER_DATA.md.
// Usage: node scripts/bake.mjs   (or: bun run bake)
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

const ROOT = new URL('../', import.meta.url);
const DIR = new URL('data/', ROOT);
const load = f => JSON.parse(readFileSync(new URL(f, DIR), 'utf8'));

// 1. Validate first (fails the build on error)
execSync('node ' + new URL('validate.mjs', import.meta.url).pathname, { stdio: 'inherit' });

// 2. Assemble the bundle
const files = readdirSync(DIR).filter(f => f.endsWith('.json'));
const ssot = {};
for (const f of files) ssot[f.replace('.json', '')] = load(f);

const bundle =
  '// GENERATED by scripts/bake.mjs — DO NOT EDIT. Edit data/*.json and run `bun run bake`.\n' +
  'window.SSOT = Object.freeze(' + JSON.stringify(ssot) + ');\n';
writeFileSync(new URL('assets/data.bundle.js', ROOT), bundle);

// 3. Generate the human-readable doc from the SSOT
const S = ssot;
const src = S.sources || {};
const cite = (id, loc) => {
  const s = src[id]; if (!s) return id;
  return `${s.short || id}${loc ? ' ' + loc : (s.locator ? ' ' + s.locator : '')}`;
};
// resolve a field's provenance (record default + _prov override)
const provOf = (rec, field) => {
  const p = (rec._prov || {})[field] || {};
  return { source: p.source || rec.source, loc: p.loc, status: p.status || rec.status || 'documented', note: p.note };
};
const rng = a => Array.isArray(a) ? `${a[0]}–${a[1]}` : a;

let md = `<!-- GENERATED from data/*.json by scripts/bake.mjs — DO NOT EDIT. Run \`bun run bake\`. -->\n\n`;
md += `# Raschpëtzer Qanat — Knowledge Base (generated)\n\n`;
md += `Generated from the SSOT (\`data/*.json\`). Every fact resolves to a primary source in \`data/sources.json\`.\n`;
md += `Dataset ${S.site.dataset.version} · ${S.site.dataset.license}.\n\n`;

md += `## Source\n\n`;
for (const [id, s] of Object.entries(src)) {
  if (id === '_doc') continue;
  md += `- **${s.short || id}** — ${s.title || ''}` +
        (s.authors ? ` (${s.authors.join('; ')}${s.year ? ', ' + s.year : ''})` : '') +
        (s.isbn ? `, ISBN ${s.isbn}` : '') + (s.url ? ` <${s.url}>` : '') +
        (s.accessed ? ` (accessed ${s.accessed})` : '') + `\n`;
}

const site = S.site.site;
md += `\n## Headline characteristics [${cite(site.source)}]\n\n`;
md += `| Property | Value | Source |\n|---|---|---|\n`;
const siteRows = [
  ['Channel length (m)', site.channelLengthM], ['Explored (m)', site.channelExploredM],
  ['Known shafts', site.shaftCountKnown], ['Shaft depth (m)', rng(site.shaftDepthRangeM)],
  ['Shaft diameter (m)', rng(site.shaftDiameterRangeM)], ['Gallery width (m)', rng(site.galleryWidthRangeM)],
  ['Gallery height (m)', rng(site.galleryHeightRangeM)], ['Avg flow (m³/day)', site.avgFlowM3PerDay],
  ['Elevation differential (m)', site.totalElevationDifferentialM],
  ['Service period (AD)', `${site.servicePeriod.fromAD}–${site.servicePeriod.toAD}`],
  ['Flow direction', site.flowDirection]
];
for (const [k, v] of siteRows) {
  const field = { 'Channel length (m)': 'channelLengthM', 'Explored (m)': 'channelExploredM',
    'Known shafts': 'shaftCountKnown', 'Avg flow (m³/day)': 'avgFlowM3PerDay' }[k];
  const p = field ? provOf(site, field) : { source: site.source };
  md += `| ${k} | ${v} | ${cite(p.source, p.loc)} |\n`;
}

md += `\n## Shafts (West → East)\n\n`;
md += `| Shaft | Role | Depth (m) | Floor (m a.s.l.) | Status | Source |\n|---|---|---|---|---|---|\n`;
for (const sh of S.shafts.shafts) {
  const dp = provOf(sh, 'depthM');
  md += `| ${sh.id} | ${sh.role} | ${sh.depthM ?? '—'} | ${sh.floorElevM ?? '—'} | ${sh.status} | ${cite(dp.source, dp.loc)} |\n`;
}
md += `\n### Shaft notes\n\n`;
for (const sh of S.shafts.shafts) {
  if (!sh.notes) continue;
  const np = provOf(sh, 'notes');
  md += `- **${sh.id}** — ${sh.notes} [${cite(np.source, np.loc)}]\n`;
}

const gal = S.gallery.gallery;
md += `\n## Gallery & channel [${cite(gal.source)}]\n\n`;
md += `- Gradient: **${gal.gradientPct}%** (${provOf(gal, 'gradientPct').note || ''}) [${cite(provOf(gal, 'gradientPct').source, provOf(gal, 'gradientPct').loc)}]\n`;
md += `- Steps: ` + gal.steps.map(s => `${s.dropM} m under ${s.underShaft}`).join('; ') + `\n`;
md += `- Channel: height ${gal.channelHeightCm} cm, width ${rng(gal.channelWidthRangeCm)} cm; flow height ${rng(gal.waterFlowHeightRangeCm)} cm; ${gal.construction}\n`;

const geo = S.geology.geology;
md += `\n## Geology [${cite(geo.source)}]\n\n`;
md += `Strata dip ~${geo.strataDipPct}% ${geo.dipDirection}. Layers (top→bottom):\n\n`;
for (const l of geo.strata) md += `- **${l.code}** — ${l.name} (${l.role})${l.thicknessRangeM ? `, ${rng(l.thicknessRangeM)} m` : ''}\n`;

const hy = S.hydrology.hydrology;
md += `\n## Hydrology [${cite(hy.source)}]\n\n`;
md += `- Flow **${hy.flowM3PerDay} m³/d** (formerly ~250); P-4 deviation ${hy.deviationAtP4M3PerDay} m³/d; seepage ${hy.seepageLossM3PerDay} m³/d\n`;
md += `- Hardness ${hy.hardnessFH} °fH · conductivity ${hy.conductivityUScm} µS/cm · pH ${hy.pH}\n`;

md += `\n## Paradata (reasoning behind modeled/inferred choices)\n\n`;
for (const [id, p] of Object.entries(S.paradata)) {
  if (id === '_doc') continue;
  md += `- **${id}** — ${p.rationale} _(${p.basis})_\n`;
}

writeFileSync(new URL('docs/RASCHPETZER_DATA.md', ROOT), md);
console.log('Baked assets/data.bundle.js + docs/RASCHPETZER_DATA.md ✓');
