// Bake real GIS vector features around the qanat into assets/vectors-walferdange.js.
// Source: Luxembourg geoportail.lu INSPIRE WFS (ACT / Service géologique), open data.
// Fetches named springs (GE.HydrogeologicalObjectNatural) and boreholes (GE.Borehole)
// for a padded window around GEO_BBOX, reprojected to WGS84 (lon/lat), and writes a
// window.RASCH_VECTORS global (loaded via <script>, like assets/data.bundle.js).
//
// Committed to the repo (the static build never refetches). Network required.
// Usage: node scripts/bake-vectors.mjs
import { writeFileSync } from 'node:fs';

// Padded a bit beyond index.html GEO_BBOX so the Surrounding-area slider can reveal more.
const AREA = { west: 6.125, east: 6.175, south: 49.655, north: 49.678 };
const BASE = 'https://wms.inspire.geoportail.lu/geoserver';

// WFS 2.0.0 bbox axis order for EPSG:4326 is lat,lon → miny,minx,maxy,maxx.
const bboxParam = [AREA.south, AREA.west, AREA.north, AREA.east, 'urn:ogc:def:crs:EPSG::4326'].join(',');
function wfsUrl(ws, typeName) {
  return `${BASE}/${ws}/ows?service=WFS&version=2.0.0&request=GetFeature`
    + `&typeNames=${typeName}&bbox=${bboxParam}`
    + `&srsName=EPSG:4326&outputFormat=application/json&count=500`;
}
async function fetchFeatures(ws, typeName) {
  const res = await fetch(wfsUrl(ws, typeName));
  const ct = res.headers.get('content-type') || '';
  if (!res.ok || !ct.includes('json')) {
    const body = await res.text().catch(() => '');
    throw new Error(`WFS ${typeName} failed: http ${res.status} ${ct}\n${body.slice(0, 300)}`);
  }
  return (await res.json()).features || [];
}
const clean = s => (s || '').replace(/\s+/g, ' ').trim();

console.log('› fetching springs + boreholes from geoportail.lu WFS …');
const springFeats = await fetchFeatures('ge', 'ge:GE.HydrogeologicalObjectNatural');
const boreFeats = await fetchFeatures('ge', 'ge:GE.Borehole');

const springs = springFeats
  .filter(f => f.geometry && f.geometry.type === 'Point')
  .map(f => ({
    lon: +f.geometry.coordinates[0].toFixed(6),
    lat: +f.geometry.coordinates[1].toFixed(6),
    name: clean(f.properties.gml_description) || 'spring',
    type: (f.properties.naturalobjecttype_xlink_href || '').split('/').pop() || 'spring'
  }));
const boreholes = boreFeats
  .filter(f => f.geometry && f.geometry.type === 'Point')
  .map(f => ({
    lon: +f.geometry.coordinates[0].toFixed(6),
    lat: +f.geometry.coordinates[1].toFixed(6),
    name: clean(f.properties.gml_description) || 'borehole'
  }));

const payload = {
  _doc: 'GENERATED by scripts/bake-vectors.mjs — real GIS vector features (geoportail.lu '
    + 'INSPIRE WFS, ACT / Service géologique du Luxembourg, open data). Rendered as 3D '
    + 'features draped on the terrain. Coords are WGS84 lon/lat.',
  meta: { source: 'geoportail_lu', service: 'geoportail.lu INSPIRE WFS', area: AREA,
          layers: ['GE.HydrogeologicalObjectNatural', 'GE.Borehole'] },
  springs, boreholes
};
const out = new URL('../assets/vectors-walferdange.js', import.meta.url);
writeFileSync(out, '// GENERATED by scripts/bake-vectors.mjs — DO NOT EDIT. Run `npm run bake:vectors`.\n'
  + 'window.RASCH_VECTORS = Object.freeze(' + JSON.stringify(payload) + ');\n');
console.log(`› wrote assets/vectors-walferdange.js (${springs.length} springs, ${boreholes.length} boreholes)`);
